const Arr = [
    {
        id: "33211",
        english: "forecast",
        transcription: "[ˈfɔːrkæst]",
        russian: "прогноз",
        tags: "Weather",
        tags_json: '["Weather"]',
    },
    {
        id: "33229",
        english: "mosquito",
        transcription: "[məˈskiː.təʊ]",
        russian: "комар",
        tags: "Animals",
        tags_json: '["Animals"]',
    },
    {
        id: "33250",
        english: "tornado",
        transcription: "[tɔːˈneɪ.dəʊ]",
        russian: "торнадо",
        tags: "Weather",
        tags_json: '["Weather"]',
    },
    {
        id: "33317",
        english: "scrooge",
        transcription: "[skruːdʒ]",
        russian: "скряга",
        tags: "",
        tags_json: '[""]',
    },
    {
        id: "33367",
        english: "cat",
        transcription: "[cæt]",
        russian: "кот",
        tags: "Animals",
        tags_json: '["Animals"]',
    },
    {
        id: "33390",
        english: "hang out",
        transcription: "|ˈhæŋ ˈaʊt|",
        russian: "тусоваться",
        tags: "Hobby",
        tags_json: '["Hobby"]',
    },
    {
        id: "33393",
        english: "girl",
        transcription: "[ɡɜːrl]",
        russian: "девочка",
        tags: "Human",
        tags_json: '["Human"]',
    },
    {
        id: "33404",
        english: "curious",
        transcription: "[ ˈkjʊrɪəs ]",
        russian: "любопытный ",
        tags: "",
        tags_json: '[""]',
    },
    {
        id: "33406",
        english: "brother",
        transcription: "[brʌðə]",
        russian: "брат",
        tags: "Family",
        tags_json: '["Family"]',
    },
    {
        id: "33407",
        english: "wind",
        transcription: "[wɪnd]",
        russian: "ветер",
        tags: "Weather",
        tags_json: '["Weather"]',
    },
    {
        id: "33409",
        english: "murky",
        transcription: "[mɜːki]",
        russian: "мрачный",
        tags: "Weather",
        tags_json: '["Weather"]',
    },
    {
        id: "33410",
        english: "red",
        transcription: "[rɛd]",
        russian: "красный",
        tags: "Colors",
        tags_json: '["Colors"]',
    },
    {
        id: "33412",
        english: "dad",
        transcription: "[dæd]",
        russian: "отец",
        tags: "Family",
        tags_json: '["Family"]',
    },
    {
        id: "33413",
        english: "yellow",
        transcription: "[jɛləʊ]",
        russian: "желтый",
        tags: "Colors",
        tags_json: '["Colors"]',
    },
    {
        id: "33414",
        english: "pan",
        transcription: "[pæn]",
        russian: "сковорода",
        tags: "Kitchen",
        tags_json: '["Kitchen"]',
    },
    {
        id: "33420",
        english: "flor",
        transcription: "[flɔː]",
        russian: "пол",
        tags: "Flat",
        tags_json: '["Flat"]',
    },
    {
        id: "33421",
        english: "step",
        transcription: "[step]",
        russian: "шаг",
        tags: "Action",
        tags_json: '["Action"]',
    },
    {
        id: "33463",
        english: "more",
        transcription: "/mɔːr/ ",
        russian: "больше",
        tags: "Comparison of Quantities",
        tags_json: '["Comparison of Quantities"]',
    },
    {
        id: "33466",
        english: "blue",
        transcription: "[blu:]",
        russian: "голубой",
        tags: "Colors",
        tags_json: '["Colors"]',
    },
    ];

    export default Arr